version: "2"

run:
  timeout: 5m
  # Skip vendor and generated code
  skip-dirs:
    - vendor

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    - asasalint                 # Detects "[]any" used as argument for variadic "func(...any)".
    - copyloopvar               # Detects places where loop variables are copied.
    - depguard
    - dogsled                   # Detects assignments with too many blank identifiers.
    - dupword                   # Detects duplicate words.
    - durationcheck             # Detect cases where two time.Duration values are being multiplied in possibly erroneous ways.
    - errorlint                 # Detects code that will cause problems with the error wrapping scheme introduced in Go 1.13.
    - errchkjson                # Detects unsupported types passed to json encoding functions and reports if checks for the returned error can be omitted.
    - exhaustive                # Detects missing options in enum switch statements.
    - exptostd                  # Detects functions from golang.org/x/exp/ that can be replaced by std functions.
    - fatcontext                # Detects nested contexts in loops and function literals.
    - forbidigo
    - gocheckcompilerdirectives # Detects invalid go compiler directive comments (//go:).
    - gocritic                  # Detects for bugs, performance and style issues.
    - gosec                     # Detects security problems.
    - govet
    - iface                     # Detects incorrect use of interfaces. Currently only used for "identical" interfaces in the same package.
    - importas
    - ineffassign
    - makezero                  # Finds slice declarations with non-zero initial length.
    - mirror                    # Detects wrong mirror patterns of bytes/strings usage.
    - misspell                  # Detects commonly misspelled English words in comments.
    - nakedret                  # Detects uses of naked returns.
    - nilnesserr                # Detects returning nil errors. It combines the features of nilness and nilerr,
    - nosprintfhostport         # Detects misuse of Sprintf to construct a host with port in a URL.
    - reassign                  # Detects reassigning a top-level variable in another package.
    - revive                    # Metalinter; drop-in replacement for golint.
    - spancheck                 # Detects mistakes with OpenTelemetry/Census spans.
    - staticcheck
    - thelper
    - unconvert                 # Detects unnecessary type conversions.
    - unused
    - usestdlibvars             # Detects the possibility to use variables/constants from the Go standard library.
    - wastedassign              # Detects wasted assignment statements.

  disable:
    - errcheck

  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: "github.com/stretchr/testify/suite"
              desc: Do not use
            - pkg: "github.com/hashicorp/go-multierror"
              desc: "Use errors.Join instead"

    forbidigo:
      forbid:
        - pkg: all
          pattern: ^(fmt\.Print(|f|ln)|print|println)$
      analyze-types: true

    gocritic:
      disabled-checks:
        - appendAssign
        - appendCombine
        - assignOp
        - builtinShadow
        - builtinShadowDecl
        - captLocal
        - commentedOutCode
        - deferInLoop
        - dupImport
        - dupSubExpr
        - elseif
        - emptyFallthrough
        - equalFold
        - evalOrder
        - exitAfterDefer
        - exposedSyncMutex
        - filepathJoin
        - hexLiteral
        - hugeParam
        - ifElseChain
        - importShadow
        - indexAlloc
        - methodExprCall
        - nestingReduce
        - nilValReturn
        - octalLiteral
        - paramTypeCombine
        - preferStringWriter
        - ptrToRefParam
        - rangeValCopy
        - redundantSprint
        - regexpMust
        - regexpSimplify
        - singleCaseSwitch
        - sloppyReassign
        - stringXbytes
        - typeAssertChain
        - typeDefFirst
        - typeUnparen
        - uncheckedInlineErr
        - unlambda
        - unnamedResult
        - unnecessaryDefer
        - unslice
        - valSwap
        - whyNoLint
      enable-all: true

    gosec:
      excludes:
        - G104 # G104: Errors unhandled; (TODO: reduce unhandled errors, or explicitly ignore)
        - G115 # G115: integer overflow conversion; (TODO: verify these: https://github.com/moby/moby/issues/48358)
        - G204 # G204: Subprocess launched with variable; too many false positives.
        - G301 # G301: Expect directory permissions to be 0750 or less (also EXC0009); too restrictive
        - G302 # G302: Expect file permissions to be 0600 or less (also EXC0009); too restrictive
        - G304 # G304: Potential file inclusion via variable.
        - G306 # G306: Expect WriteFile permissions to be 0600 or less (too restrictive; also flags "0o644" permissions)
        - G307 # G307: Deferring unsafe method "*os.File" on type "Close" (also EXC0008); (TODO: evaluate these and fix where needed: G307: Deferring unsafe method "*os.File" on type "Close")
        - G504 # G504: Blocklisted import net/http/cgi: Go versions < 1.6.3 are vulnerable to Httpoxy attack: (CVE-2016-5386); (only affects go < 1.6.3)

    govet:
      enable-all: true
      disable:
        - fieldalignment # TODO: evaluate which ones should be updated.

    revive:
      # Only listed rules are applied
      # https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md
      rules:
        - name: increment-decrement
          # FIXME make sure all packages have a description. Currently, there's many packages without.
        - name: package-comments
          disabled: true
        - name: redefines-builtin-id
        - name: superfluous-else
          arguments:
            - preserve-scope
          # FIXME(doringeman): Fix this in a follow-up PR so the initial one which adds linting is not too noisy.
        - name: use-any
          disabled: true
          # TODO: evaluate whether it makes sense.
        - name: use-errors-new
          disabled: true
        - name: var-declaration

    staticcheck:
      checks:
        - all
        - -QF1008 # Omit embedded fields from selector expression; https://staticcheck.dev/docs/checks/#QF1008
        - -ST1000 # Incorrect or missing package comment; https://staticcheck.dev/docs/checks/#ST1000
        - -ST1003 # Poorly chosen identifier; https://staticcheck.dev/docs/checks/#ST1003
        - -ST1005 # Incorrectly formatted error string; https://staticcheck.dev/docs/checks/#ST1005

    thelper:
      test:
        # Check *testing.T is first param (or after context.Context) of helper function.
        first: false
        # Check t.Helper() begins helper function.
        begin: false
      benchmark:
        # Check *testing.B is first param (or after context.Context) of helper function.
        first: false
        # Check b.Helper() begins helper function.
        begin: false
      tb:
        # Check *testing.TB is first param (or after context.Context) of helper function.
        first: false
        # Check *testing.TB param has name tb.
        name: false
        # Check tb.Helper() begins helper function.
        begin: false
      fuzz:
        # Check *testing.F is first param (or after context.Context) of helper function.
        first: false
        # Check f.Helper() begins helper function.
        begin: false

  exclusions:
    rules:
    # We prefer to use an "linters.exclusions.rules" so that new "default" exclusions are not
    # automatically inherited. We can decide whether or not to follow upstream
    # defaults when updating golang-ci-lint versions.
    # Unfortunately, this means we have to copy the whole exclusion pattern, as
    # (unlike the "include" option), the "exclude" option does not take exclusion
    # ID's.
    #
    # These exclusion patterns are copied from the default excludes at:
    # https://github.com/golangci/golangci-lint/blob/v1.61.0/pkg/config/issues.go#L11-L104
    #
    # The default list of exclusions can be found at:
    # https://golangci-lint.run/usage/false-positives/#default-exclusions

    # Exclude some linters from running on tests files.
      - text: '^shadow: declaration of "(ctx|err|ok)" shadows declaration'
        linters:
          - govet

issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
